-- 012-umra-tours.sql
-- Умра как бронируемые туры: 9 программ = 9 туров под направлением «Умра»,
-- заезды по явным датам, цены за человека по типу номера QUAD/TRPL/DBL
-- (детских тарифов нет). Данные реальные, из курируемого списка оператора
-- (tools/build-seed.py → UMRA_PROGRAMS). Осенние «еженедельные» даты пока не
-- заводятся — добавим точным списком, когда оператор пришлёт числа.
--
-- Идемпотентна: сначала удаляет всё по направлению «Умра», потом вставляет
-- заново. Заезды/цены/агентства Карадениза и брони по нему НЕ трогает.
-- ВНИМАНИЕ: удаляет заезды Умры — если по ним УЖЕ есть брони, повторный
-- прогон их осиротит. На момент первого добавления броней по Умре нет.
--
-- Прогон (оператор, wrangler залогинен):
--   cd worker
--   wrangler d1 execute turon-tour --remote --file=../db/migrations/012-umra-tours.sql

DELETE FROM departure_prices WHERE departure_id IN (
  SELECT d.id FROM departures d JOIN tours t ON t.id = d.tour_id WHERE t.destination = 'Умра');
DELETE FROM departures WHERE tour_id IN (SELECT id FROM tours WHERE destination = 'Умра');
DELETE FROM tour_content WHERE tour_id IN (SELECT id FROM tours WHERE destination = 'Умра');
DELETE FROM tours WHERE destination = 'Умра';
DELETE FROM destinations WHERE name = 'Умра';

INSERT INTO destinations (name, title, blurb, image, sort) VALUES ('Умра', 'Умра · Мекка и Медина', 'Паломничество: Мекка, Медина, Джидда', '', 2);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_TAJ13', 'Умра · TAJ-13', 'Умра', 0, 0, 1, 'Август—сентябрь еженедельно; осенние заезды (октябрь—декабрь) уточняются у оператора.', 'Умра по программе TAJ-13 (13 дней / 12 ночей). Ташкент → Джидда → Мекка → Медина → Ташкент. Джидда · Hawada Hotel Jeddah · 1 ночь; Мекка · Taj Park · 990 м до Харама · 8 ночей; Медина · Grand Al Shahba · 250 м до мечети Пророка · 3 ночи.', 12);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_TAJ13P', 'Умра · TAJ-13+', 'Умра', 0, 0, 1, 'Июль—август по указанным датам.', 'Умра по программе TAJ-13+ (13 дней / 12 ночей). Ташкент → Джидда → Мекка → Медина → Ташкент. Джидда · Hawada Hotel Jeddah · 1 ночь; Мекка · Taj Park · 990 м до Харама · 8 ночей; Медина · Mukhtara Plaza · 250 м до мечети Пророка · 3 ночи.', 12);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_ANJUM13', 'Умра · ANJUM-13', 'Умра', 0, 0, 1, 'Август по указанным датам.', 'Умра по программе ANJUM-13 (13 дней / 12 ночей). Ташкент → Джидда → Мекка → Медина → Ташкент. Джидда · Hawada Hotel Jeddah · 1 ночь; Мекка · Anjum · 250 м до Харама · 8 ночей; Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи.', 12);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_SHOHADA13', 'Умра · SHOHADA-13', 'Умра', 0, 0, 1, 'Август по указанным датам.', 'Умра по программе SHOHADA-13 (13 дней / 12 ночей). Ташкент → Джидда → Мекка → Медина → Ташкент. Джидда · Hawada Hotel Jeddah · 1 ночь; Мекка · Al Shohada · 250 м до Харама · 8 ночей; Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи.', 12);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_JUMEIRAH13', 'Умра · JUMEIRAH-13', 'Умра', 0, 0, 1, 'Август по указанным датам.', 'Умра по программе JUMEIRAH-13 (13 дней / 12 ночей). Ташкент → Джидда → Мекка → Медина → Ташкент. Джидда · Hawada Hotel Jeddah · 1 ночь; Мекка · Jumeirah Hotel · 100 м до Харама · 8 ночей; Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи.', 12);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_SAJA10', 'Умра · SAJA-10', 'Умра', 0, 0, 1, 'Июль—сентябрь еженедельно; осенние заезды (октябрь—декабрь) уточняются у оператора.', 'Умра по программе SAJA-10 (10 дней / 9 ночей). Ташкент → Медина → Мекка → Джидда → Ташкент. Медина · Saja Al-Madinah · 250 м до мечети Пророка · 4 ночи; Мекка · Taj Park · 990 м до Харама · 5 ночей.', 9);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_SWISS10', 'Умра · SWISSOTEL-10', 'Умра', 0, 0, 1, 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.', 'Умра по программе SWISSOTEL-10 (10 дней / 9 ночей). Ташкент → Медина → Мекка → Джидда → Ташкент. Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи; Мекка · Swissotel Makkah · 50 м до Харама · 5 ночей.', 9);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_ANJUM10', 'Умра · ANJUM-10', 'Умра', 0, 0, 1, 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.', 'Умра по программе ANJUM-10 (10 дней / 9 ночей). Ташкент → Медина → Мекка → Джидда → Ташкент. Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи; Мекка · Anjum Makkah · 250 м до Харама · 5 ночей.', 9);
INSERT INTO tours (code, name, destination, agency_commission, operator_commission, is_bookable, note, description, nights) VALUES ('UMRA_JUMEIRAH10', 'Умра · JUMEIRAH-10', 'Умра', 0, 0, 1, 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.', 'Умра по программе JUMEIRAH-10 (10 дней / 9 ночей). Ташкент → Медина → Мекка → Джидда → Ташкент. Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи; Мекка · Jumeirah Jabal Omar · 100 м до Харама · 5 ночей.', 9);
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–JED 06:20–11:10 · MED–TAS 17:30–01:50' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Джидда · Hawada Hotel Jeddah · 1 ночь' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Taj Park · 990 м до Харама · 8 ночей' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Медина · Grand Al Shahba · 250 м до мечети Пророка · 3 ночи' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Автобус Мекка—Медина' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Трёхразовое питание в Мекке и Медине' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, '1 питание в Джидде' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 8, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Август—сентябрь еженедельно; осенние заезды (октябрь—декабрь) уточняются у оператора.', NULL FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–JED 06:20–11:10 · MED–TAS 17:30–01:50' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Джидда · Hawada Hotel Jeddah · 1 ночь' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Taj Park · 990 м до Харама · 8 ночей' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Медина · Mukhtara Plaza · 250 м до мечети Пророка · 3 ночи' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Скоростной поезд Мекка—Медина' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Питание: Джидда 1 раз, Мекка 3 раза, Медина 2 раза (шведский стол)' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Виза' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 8, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Июль—август по указанным датам.', NULL FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–JED 06:20–11:10 · MED–TAS 17:30–01:50' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Джидда · Hawada Hotel Jeddah · 1 ночь' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Anjum · 250 м до Харама · 8 ночей' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Скоростной поезд Мекка—Медина' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Питание: Джидда 1 раз, Мекка 1 раз, Медина 2 раза (шведский стол)' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Виза' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 8, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Август по указанным датам.', NULL FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–JED 06:20–11:10 · MED–TAS 17:30–01:50' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Джидда · Hawada Hotel Jeddah · 1 ночь' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Al Shohada · 250 м до Харама · 8 ночей' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Скоростной поезд Мекка—Медина' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Питание: Джидда 1 раз, Мекка и Медина 2 раза (шведский стол)' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Виза' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 8, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Август по указанным датам.', NULL FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–JED 06:20–11:10 · MED–TAS 17:30–01:50' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Джидда · Hawada Hotel Jeddah · 1 ночь' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Jumeirah Hotel · 100 м до Харама · 8 ночей' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Скоростной поезд Мекка—Медина' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Питание: Джидда 1 раз, Мекка 1 раз, Медина 2 раза (шведский стол)' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Виза' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 8, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Август по указанным датам.', NULL FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–MED 11:00–15:50 · JED–TAS 12:40–21:20' FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Медина · Saja Al-Madinah · 250 м до мечети Пророка · 4 ночи' FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Taj Park · 990 м до Харама · 5 ночей' FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Скоростной поезд Медина—Мекка' FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Трёхразовое питание' FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Виза' FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Июль—сентябрь еженедельно; осенние заезды (октябрь—декабрь) уточняются у оператора.', NULL FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–MED 11:00–15:50 · JED–TAS 12:40–21:20' FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи' FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Swissotel Makkah · 50 м до Харама · 5 ночей' FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Скоростной поезд Медина—Мекка' FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Питание: Мекка 1 раз, Медина 2 раза (шведский стол)' FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Виза' FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.', NULL FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–MED 11:00–15:50 · JED–TAS 12:40–21:20' FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи' FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Anjum Makkah · 250 м до Харама · 5 ночей' FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Скоростной поезд Медина—Мекка' FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Питание: Мекка 1 раз, Медина 2 раза (шведский стол)' FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Виза' FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.', NULL FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 1, 'Centrum Air · TAS–MED 11:00–15:50 · JED–TAS 12:40–21:20' FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 2, 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи' FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 3, 'Мекка · Jumeirah Jabal Omar · 100 м до Харама · 5 ночей' FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 4, 'Скоростной поезд Медина—Мекка' FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 5, 'Питание в Мекке и Медине 2 раза (шведский стол)' FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 6, 'Виза' FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO tour_content (tour_id, kind, sort, text) SELECT id, 'included', 7, 'Руководители группы и врачи' FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO tour_content (tour_id, kind, sort, text, url) SELECT id, 'info', 1, 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.', NULL FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0801', '2026-08-01', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0801';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0808', '2026-08-08', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0808';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0815', '2026-08-15', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0815';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0822', '2026-08-22', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0822';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0829', '2026-08-29', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0829';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0829';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0829';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0905', '2026-09-05', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0905';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0905';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0905';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0912', '2026-09-12', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0912';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0912';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0912';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0919', '2026-09-19', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0919';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0919';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0919';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13-0926', '2026-09-26', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0926';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0926';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13-0926';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13P-0718', '2026-07-18', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0718';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1300, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0718';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1400, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0718';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13P-0725', '2026-07-25', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0725';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1300, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0725';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1400, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0725';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13P-0801', '2026-08-01', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1300, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1400, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0801';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13P-0808', '2026-08-08', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1300, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1400, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0808';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13P-0815', '2026-08-15', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1300, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1400, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0815';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_TAJ13P-0822', '2026-08-22', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_TAJ13P';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1300, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1400, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_TAJ13P-0822';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_ANJUM13-0801', '2026-08-01', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1600, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1700, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1800, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0801';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_ANJUM13-0808', '2026-08-08', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1600, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1700, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1800, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0808';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_ANJUM13-0815', '2026-08-15', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1600, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1700, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1800, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0815';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_ANJUM13-0822', '2026-08-22', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_ANJUM13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1600, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1700, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1800, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM13-0822';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SHOHADA13-0801', '2026-08-01', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1650, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1750, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1850, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0801';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SHOHADA13-0808', '2026-08-08', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1650, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1750, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1850, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0808';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SHOHADA13-0815', '2026-08-15', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1650, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1750, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1850, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0815';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SHOHADA13-0822', '2026-08-22', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SHOHADA13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1650, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1750, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1850, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SHOHADA13-0822';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_JUMEIRAH13-0801', '2026-08-01', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1900, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 2000, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0801';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 2200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0801';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_JUMEIRAH13-0808', '2026-08-08', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1900, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 2000, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0808';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 2200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0808';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_JUMEIRAH13-0815', '2026-08-15', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1900, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 2000, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0815';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 2200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0815';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_JUMEIRAH13-0822', '2026-08-22', 'JED', 0, 45, 0 FROM tours WHERE code = 'UMRA_JUMEIRAH13';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1900, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 2000, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0822';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 2200, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH13-0822';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0730', '2026-07-30', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0730';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0730';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0730';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0806', '2026-08-06', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0806';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0806';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0806';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0813', '2026-08-13', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0813';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0813';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0813';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0820', '2026-08-20', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0820';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0820';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0820';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0827', '2026-08-27', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0827';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0827';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0827';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0903', '2026-09-03', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0903';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0903';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0903';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0910', '2026-09-10', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0910';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0910';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0910';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0917', '2026-09-17', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0917';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0917';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0917';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SAJA10-0924', '2026-09-24', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SAJA10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1250, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0924';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1350, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0924';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1450, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SAJA10-0924';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_SWISS10-0730', '2026-07-30', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_SWISS10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1650, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SWISS10-0730';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1750, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SWISS10-0730';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1900, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_SWISS10-0730';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_ANJUM10-0730', '2026-07-30', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_ANJUM10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1600, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM10-0730';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1700, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_ANJUM10-0730';
INSERT INTO departures (tour_id, code, date_start, transport, is_info_tour, capacity, seats_taken) SELECT id, 'UMRA_JUMEIRAH10-0730', '2026-07-30', 'MED', 0, 45, 0 FROM tours WHERE code = 'UMRA_JUMEIRAH10';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'QUAD', 'Четырёхместный (QUAD)', 'placement', 1750, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH10-0730';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'TRPL', 'Трёхместный (TRPL)', 'placement', 1890, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH10-0730';
INSERT INTO departure_prices (departure_id, code, label, kind, price, age_from, age_to, occupies_seat) SELECT id, 'DBL', 'Двухместный (DBL)', 'placement', 1990, NULL, NULL, 1 FROM departures WHERE code = 'UMRA_JUMEIRAH10-0730';
