-- 017 — переводы наполнения (uz/en/tr) для УЖЕ РАБОТАЮЩЕЙ базы.
--
-- Сгенерировано tools/build-i18n-migration.py. Руками не править:
-- правьте tools/seed-i18n.py и пересоберите.
--
-- Требует миграции 016 (колонки i18n). Идемпотентна: только UPDATE,
-- ничего не удаляет и не создаёт. Заезды, цены, брони и агентства
-- не затрагивает вообще.
--
-- Строки ищутся ПО РУССКОМУ ТЕКСТУ: id в боевой базе свои. Если
-- оператор уже переписал текст строки через редактор, перевод по ней
-- не найдётся и строка останется русской — это лучше, чем подставить
-- перевод к другому тексту.

UPDATE tours SET i18n = '{"uz": {"name": "Batumi - Rize - Trabzon", "note": "Har haftalik jo‘nashlar, narxlar joylashuv turiga qarab", "description": "Qora dengiz bo‘ylab kombinatsiyalangan guruh turi: 8 kunda Batumi, Rize va Trabzon. O‘zbek gid hamrohligi, 15 dan ortiq ekskursiya, birinchi qator sohil mehmonxonalari, Sprinter mikroavtobuslarida transferlar va gruzin oilasida kechki ovqat."}, "en": {"name": "Batumi – Rize – Trabzon", "note": "Weekly departures, prices by room type", "description": "A combined group tour of the Black Sea: Batumi, Rize and Trabzon in 8 days. An Uzbek guide throughout, more than 15 excursions, seafront hotels, Sprinter minibus transfers and dinner with a Georgian family."}, "tr": {"name": "Batum - Rize - Trabzon", "note": "Haftalık hareketler, fiyatlar oda tipine göre", "description": "Karadeniz boyunca kombine grup turu: 8 günde Batum, Rize ve Trabzon. Özbek rehber eşliğinde, 15’ten fazla gezi, sahil hattında oteller, Sprinter minibüslerle transferler ve bir Gürcü ailesinde akşam yemeği."}}' WHERE code = 'KARADENIZ';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · TAJ-13", "description": "TAJ-13 dasturi bo‘yicha umra (13 kun / 12 kecha). Toshkent → Jidda → Makka → Madina → Toshkent. Jidda · Hawada Hotel Jeddah · 1 kecha; Makka · Taj Park · Haramgacha 990 m · 8 kecha; Madina · Grand Al Shahba · Payg‘ambar masjidigacha 250 m · 3 kecha.", "note": "Avgust—sentabr har hafta; kuzgi jo‘nashlar (oktabr—dekabr) operator bilan aniqlanadi."}, "en": {"name": "Umrah · TAJ-13", "description": "Umrah under the TAJ-13 programme (13 days / 12 nights). Tashkent → Jeddah → Mecca → Medina → Tashkent. Jeddah · Hawada Hotel Jeddah · 1 night; Mecca · Taj Park · 990 m to the Haram · 8 nights; Medina · Grand Al Shahba · 250 m to the Prophet’s Mosque · 3 nights.", "note": "Weekly in August–September; autumn departures (October–December) to be confirmed with the operator."}, "tr": {"name": "Umre · TAJ-13", "description": "TAJ-13 programıyla umre (13 gün / 12 gece). Taşkent → Cidde → Mekke → Medine → Taşkent. Cidde · Hawada Hotel Jeddah · 1 gece; Mekke · Taj Park · Harem’e 990 m · 8 gece; Medine · Grand Al Shahba · Mescid-i Nebevi’ye 250 m · 3 gece.", "note": "Ağustos–Eylül her hafta; sonbahar hareketleri (Ekim–Aralık) operatörle netleştirilir."}}' WHERE code = 'UMRA_TAJ13';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · TAJ-13+", "description": "TAJ-13+ dasturi bo‘yicha umra (13 kun / 12 kecha). Toshkent → Jidda → Makka → Madina → Toshkent. Jidda · Hawada Hotel Jeddah · 1 kecha; Makka · Taj Park · Haramgacha 990 m · 8 kecha; Madina · Mukhtara Plaza · Payg‘ambar masjidigacha 250 m · 3 kecha.", "note": "Iyul—avgust — ko‘rsatilgan sanalarda."}, "en": {"name": "Umrah · TAJ-13+", "description": "Umrah under the TAJ-13+ programme (13 days / 12 nights). Tashkent → Jeddah → Mecca → Medina → Tashkent. Jeddah · Hawada Hotel Jeddah · 1 night; Mecca · Taj Park · 990 m to the Haram · 8 nights; Medina · Mukhtara Plaza · 250 m to the Prophet’s Mosque · 3 nights.", "note": "July–August, on the dates listed."}, "tr": {"name": "Umre · TAJ-13+", "description": "TAJ-13+ programıyla umre (13 gün / 12 gece). Taşkent → Cidde → Mekke → Medine → Taşkent. Cidde · Hawada Hotel Jeddah · 1 gece; Mekke · Taj Park · Harem’e 990 m · 8 gece; Medine · Mukhtara Plaza · Mescid-i Nebevi’ye 250 m · 3 gece.", "note": "Temmuz–Ağustos, belirtilen tarihlerde."}}' WHERE code = 'UMRA_TAJ13P';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · ANJUM-13", "description": "ANJUM-13 dasturi bo‘yicha umra (13 kun / 12 kecha). Toshkent → Jidda → Makka → Madina → Toshkent. Jidda · Hawada Hotel Jeddah · 1 kecha; Makka · Anjum · Haramgacha 250 m · 8 kecha; Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 3 kecha.", "note": "Avgust — ko‘rsatilgan sanalarda."}, "en": {"name": "Umrah · ANJUM-13", "description": "Umrah under the ANJUM-13 programme (13 days / 12 nights). Tashkent → Jeddah → Mecca → Medina → Tashkent. Jeddah · Hawada Hotel Jeddah · 1 night; Mecca · Anjum · 250 m to the Haram · 8 nights; Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 3 nights.", "note": "August, on the dates listed."}, "tr": {"name": "Umre · ANJUM-13", "description": "ANJUM-13 programıyla umre (13 gün / 12 gece). Taşkent → Cidde → Mekke → Medine → Taşkent. Cidde · Hawada Hotel Jeddah · 1 gece; Mekke · Anjum · Harem’e 250 m · 8 gece; Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 3 gece.", "note": "Ağustos, belirtilen tarihlerde."}}' WHERE code = 'UMRA_ANJUM13';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · SHOHADA-13", "description": "SHOHADA-13 dasturi bo‘yicha umra (13 kun / 12 kecha). Toshkent → Jidda → Makka → Madina → Toshkent. Jidda · Hawada Hotel Jeddah · 1 kecha; Makka · Al Shohada · Haramgacha 250 m · 8 kecha; Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 3 kecha.", "note": "Avgust — ko‘rsatilgan sanalarda."}, "en": {"name": "Umrah · SHOHADA-13", "description": "Umrah under the SHOHADA-13 programme (13 days / 12 nights). Tashkent → Jeddah → Mecca → Medina → Tashkent. Jeddah · Hawada Hotel Jeddah · 1 night; Mecca · Al Shohada · 250 m to the Haram · 8 nights; Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 3 nights.", "note": "August, on the dates listed."}, "tr": {"name": "Umre · SHOHADA-13", "description": "SHOHADA-13 programıyla umre (13 gün / 12 gece). Taşkent → Cidde → Mekke → Medine → Taşkent. Cidde · Hawada Hotel Jeddah · 1 gece; Mekke · Al Shohada · Harem’e 250 m · 8 gece; Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 3 gece.", "note": "Ağustos, belirtilen tarihlerde."}}' WHERE code = 'UMRA_SHOHADA13';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · JUMEIRAH-13", "description": "JUMEIRAH-13 dasturi bo‘yicha umra (13 kun / 12 kecha). Toshkent → Jidda → Makka → Madina → Toshkent. Jidda · Hawada Hotel Jeddah · 1 kecha; Makka · Jumeirah Hotel · Haramgacha 100 m · 8 kecha; Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 3 kecha.", "note": "Avgust — ko‘rsatilgan sanalarda."}, "en": {"name": "Umrah · JUMEIRAH-13", "description": "Umrah under the JUMEIRAH-13 programme (13 days / 12 nights). Tashkent → Jeddah → Mecca → Medina → Tashkent. Jeddah · Hawada Hotel Jeddah · 1 night; Mecca · Jumeirah Hotel · 100 m to the Haram · 8 nights; Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 3 nights.", "note": "August, on the dates listed."}, "tr": {"name": "Umre · JUMEIRAH-13", "description": "JUMEIRAH-13 programıyla umre (13 gün / 12 gece). Taşkent → Cidde → Mekke → Medine → Taşkent. Cidde · Hawada Hotel Jeddah · 1 gece; Mekke · Jumeirah Hotel · Harem’e 100 m · 8 gece; Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 3 gece.", "note": "Ağustos, belirtilen tarihlerde."}}' WHERE code = 'UMRA_JUMEIRAH13';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · SAJA-10", "description": "SAJA-10 dasturi bo‘yicha umra (10 kun / 9 kecha). Toshkent → Madina → Makka → Jidda → Toshkent. Madina · Saja Al-Madinah · Payg‘ambar masjidigacha 250 m · 4 kecha; Makka · Taj Park · Haramgacha 990 m · 5 kecha.", "note": "Iyul—sentabr har hafta; kuzgi jo‘nashlar (oktabr—dekabr) operator bilan aniqlanadi."}, "en": {"name": "Umrah · SAJA-10", "description": "Umrah under the SAJA-10 programme (10 days / 9 nights). Tashkent → Medina → Mecca → Jeddah → Tashkent. Medina · Saja Al-Madinah · 250 m to the Prophet’s Mosque · 4 nights; Mecca · Taj Park · 990 m to the Haram · 5 nights.", "note": "Weekly in July–September; autumn departures (October–December) to be confirmed with the operator."}, "tr": {"name": "Umre · SAJA-10", "description": "SAJA-10 programıyla umre (10 gün / 9 gece). Taşkent → Medine → Mekke → Cidde → Taşkent. Medine · Saja Al-Madinah · Mescid-i Nebevi’ye 250 m · 4 gece; Mekke · Taj Park · Harem’e 990 m · 5 gece.", "note": "Temmuz–Eylül her hafta; sonbahar hareketleri (Ekim–Aralık) operatörle netleştirilir."}}' WHERE code = 'UMRA_SAJA10';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · SWISSOTEL-10", "description": "SWISSOTEL-10 dasturi bo‘yicha umra (10 kun / 9 kecha). Toshkent → Madina → Makka → Jidda → Toshkent. Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 4 kecha; Makka · Swissotel Makkah · Haramgacha 50 m · 5 kecha.", "note": "6 avgustdan 3 dekabrgacha har hafta — aniq sanalar operator bilan aniqlanadi."}, "en": {"name": "Umrah · SWISSOTEL-10", "description": "Umrah under the SWISSOTEL-10 programme (10 days / 9 nights). Tashkent → Medina → Mecca → Jeddah → Tashkent. Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 4 nights; Mecca · Swissotel Makkah · 50 m to the Haram · 5 nights.", "note": "Weekly from 6 August to 3 December — exact dates to be confirmed with the operator."}, "tr": {"name": "Umre · SWISSOTEL-10", "description": "SWISSOTEL-10 programıyla umre (10 gün / 9 gece). Taşkent → Medine → Mekke → Cidde → Taşkent. Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 4 gece; Mekke · Swissotel Makkah · Harem’e 50 m · 5 gece.", "note": "6 Ağustos–3 Aralık arası her hafta — kesin tarihler operatörle netleştirilir."}}' WHERE code = 'UMRA_SWISS10';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · ANJUM-10", "description": "ANJUM-10 dasturi bo‘yicha umra (10 kun / 9 kecha). Toshkent → Madina → Makka → Jidda → Toshkent. Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 4 kecha; Makka · Anjum Makkah · Haramgacha 250 m · 5 kecha.", "note": "6 avgustdan 3 dekabrgacha har hafta — aniq sanalar operator bilan aniqlanadi."}, "en": {"name": "Umrah · ANJUM-10", "description": "Umrah under the ANJUM-10 programme (10 days / 9 nights). Tashkent → Medina → Mecca → Jeddah → Tashkent. Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 4 nights; Mecca · Anjum Makkah · 250 m to the Haram · 5 nights.", "note": "Weekly from 6 August to 3 December — exact dates to be confirmed with the operator."}, "tr": {"name": "Umre · ANJUM-10", "description": "ANJUM-10 programıyla umre (10 gün / 9 gece). Taşkent → Medine → Mekke → Cidde → Taşkent. Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 4 gece; Mekke · Anjum Makkah · Harem’e 250 m · 5 gece.", "note": "6 Ağustos–3 Aralık arası her hafta — kesin tarihler operatörle netleştirilir."}}' WHERE code = 'UMRA_ANJUM10';
UPDATE tours SET i18n = '{"uz": {"name": "Umra · JUMEIRAH-10", "description": "JUMEIRAH-10 dasturi bo‘yicha umra (10 kun / 9 kecha). Toshkent → Madina → Makka → Jidda → Toshkent. Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 4 kecha; Makka · Jumeirah Jabal Omar · Haramgacha 100 m · 5 kecha.", "note": "6 avgustdan 3 dekabrgacha har hafta — aniq sanalar operator bilan aniqlanadi."}, "en": {"name": "Umrah · JUMEIRAH-10", "description": "Umrah under the JUMEIRAH-10 programme (10 days / 9 nights). Tashkent → Medina → Mecca → Jeddah → Tashkent. Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 4 nights; Mecca · Jumeirah Jabal Omar · 100 m to the Haram · 5 nights.", "note": "Weekly from 6 August to 3 December — exact dates to be confirmed with the operator."}, "tr": {"name": "Umre · JUMEIRAH-10", "description": "JUMEIRAH-10 programıyla umre (10 gün / 9 gece). Taşkent → Medine → Mekke → Cidde → Taşkent. Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 4 gece; Mekke · Jumeirah Jabal Omar · Harem’e 100 m · 5 gece.", "note": "6 Ağustos–3 Aralık arası her hafta — kesin tarihler operatörle netleştirilir."}}' WHERE code = 'UMRA_JUMEIRAH10';

UPDATE destinations SET i18n = '{"uz": {"title": "Turkiya va Gruziya", "blurb": "Qora dengiz sohili: Trabzon, Rize, Batumi"}, "en": {"title": "Türkiye and Georgia", "blurb": "The Black Sea coast: Trabzon, Rize, Batumi"}, "tr": {"title": "Türkiye ve Gürcistan", "blurb": "Karadeniz kıyısı: Trabzon, Rize, Batum"}}' WHERE name = 'Турция';
UPDATE destinations SET i18n = '{"uz": {"title": "Umra · Makka va Madina", "blurb": "Ziyorat: Makka, Madina, Jidda"}, "en": {"title": "Umrah · Mecca and Medina", "blurb": "Pilgrimage: Mecca, Medina, Jeddah"}, "tr": {"title": "Umre · Mekke ve Medine", "blurb": "Hac ziyareti: Mekke, Medine, Cidde"}}' WHERE name = 'Умра';

UPDATE tour_variants SET i18n = '{"uz": {"title": "Batumi → Rize · Batumiga qo‘nish, Trabzondan uchish"}, "en": {"title": "Batumi → Rize · arrive in Batumi, depart from Trabzon"}, "tr": {"title": "Batum → Rize · Batum’a iniş, Trabzon’dan kalkış"}}' WHERE code = 'A' AND tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ');
UPDATE tour_variants SET i18n = '{"uz": {"title": "Rize → Batumi · Trabzonga qo‘nish, Batumidan uchish"}, "en": {"title": "Rize → Batumi · arrive in Trabzon, depart from Batumi"}, "tr": {"title": "Rize → Batum · Trabzon’a iniş, Batum’dan kalkış"}}' WHERE code = 'B' AND tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ');

UPDATE tour_content SET i18n = '{"uz": {"text": "Toshkent — Trabzon / Batumi aviabiletlari"}, "en": {"text": "Tashkent — Trabzon / Batumi flights"}, "tr": {"text": "Taşkent — Trabzon / Batum uçak biletleri"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Авиабилеты Ташкент — Трабзон / Батуми';
UPDATE tour_content SET i18n = '{"uz": {"text": "Birinchi qator sohil mehmonxonalarida nonushta bilan 7 kecha: Batumi View Luxury (Batumi) va Rhisos Gold Otel Rize (Rize)"}, "en": {"text": "7 nights with breakfast in seafront hotels: Batumi View Luxury (Batumi) and Rhisos Gold Otel Rize (Rize)"}, "tr": {"text": "Sahil hattındaki otellerde kahvaltı dahil 7 gece: Batumi View Luxury (Batum) ve Rhisos Gold Otel Rize (Rize)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Проживание 7 ночей на базе завтраков в отелях на первой береговой линии: Batumi View Luxury (Батуми) и Rhisos Gold Otel Rize (Ризе)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Butun safar davriga tibbiy sug‘urta"}, "en": {"text": "Medical insurance for the whole trip"}, "tr": {"text": "Tüm seyahat süresi için sağlık sigortası"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Медицинская страховка на весь период поездки';
UPDATE tour_content SET i18n = '{"uz": {"text": "Barcha transferlar Sprinter mikroavtobuslarida"}, "en": {"text": "All transfers between locations by Sprinter minibus"}, "tr": {"text": "Noktalar arası tüm transferler Sprinter minibüslerle"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Все трансферы между локациями на микроавтобусах Sprinter';
UPDATE tour_content SET i18n = '{"uz": {"text": "Batumi yaqinidagi gruzin oilasida bitta gastronomik kechki ovqat (Mahuntseti) — halol menyu"}, "en": {"text": "One food-tasting dinner with a Georgian family near Batumi (Makhuntseti) — halal menu"}, "tr": {"text": "Batum yakınında bir Gürcü ailesinde gastronomi akşam yemeği (Mahuntseti) — helal menü"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Один гастрономический ужин в грузинской семье под Батуми (Махунцети) — халяльное меню';
UPDATE tour_content SET i18n = '{"uz": {"text": "Rus tilida so‘zlashuvchi o‘zbek gid hamrohligi"}, "en": {"text": "A Russian-speaking Uzbek guide throughout"}, "tr": {"text": "Rusça konuşan Özbek rehber eşliği"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Сопровождение русскоговорящего узбекского гида';
UPDATE tour_content SET i18n = '{"uz": {"text": "Dastur bo‘yicha 15 dan ortiq ekskursiya"}, "en": {"text": "More than 15 excursions in the programme"}, "tr": {"text": "Programda 15’ten fazla gezi"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Более 15 экскурсий по программе';
UPDATE tour_content SET i18n = '{"uz": {"text": "Safar davomida 24/7 qo‘llab-quvvatlash"}, "en": {"text": "24/7 support during the trip"}, "tr": {"text": "Seyahat boyunca 24/7 destek"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'included' AND text = 'Поддержка 24/7 на протяжении поездки';
UPDATE tour_content SET i18n = '{"uz": {"text": "Dastur tashqarisidagi tushlik va kechki ovqatlar (Batumidagi bitta gastronomik kechki ovqatdan tashqari)"}, "en": {"text": "Lunches and dinners outside the programme (except the one food-tasting dinner near Batumi)"}, "tr": {"text": "Program dışı öğle ve akşam yemekleri (Batum’daki tek gastronomi yemeği hariç)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'excluded' AND text = 'Обеды и ужины вне программы (кроме одного гастрономического ужина в Батуми)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Muzeylarga va pullik obyektlarga kirish chiptalari"}, "en": {"text": "Entrance tickets to museums and paid sites"}, "tr": {"text": "Müze ve ücretli mekân giriş biletleri"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'excluded' AND text = 'Входные билеты в музеи и на платные объекты';
UPDATE tour_content SET i18n = '{"uz": {"text": "Batumidagi delfinariy"}, "en": {"text": "The Batumi dolphinarium"}, "tr": {"text": "Batum yunus akvaryumu"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'excluded' AND text = 'Дельфинарий в Батуми';
UPDATE tour_content SET i18n = '{"uz": {"text": "Mahuntsetidagi zipline"}, "en": {"text": "The zipline in Makhuntseti"}, "tr": {"text": "Mahuntseti’de zipline"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'excluded' AND text = 'Зиплайн в Махунцети';
UPDATE tour_content SET i18n = '{"uz": {"text": "Rizedagi qo‘shimcha ekskursiyalar: Duatepe, Ceceve Bahcesi"}, "en": {"text": "Optional excursions in Rize: Duatepe, Ceceve Bahcesi"}, "tr": {"text": "Rize’de ek geziler: Duatepe, Ceceve Bahçesi"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'excluded' AND text = 'Дополнительные экскурсии в Ризе: Duatepe, Ceceve Bahcesi';
UPDATE tour_content SET i18n = '{"uz": {"text": "Shaxsiy xarajatlar"}, "en": {"text": "Personal expenses"}, "tr": {"text": "Kişisel harcamalar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'excluded' AND text = 'Личные расходы';
UPDATE tour_content SET i18n = '{"uz": {"text": "Gruziya O‘zbekiston fuqarolari uchun vizasiz — xorijiy pasport bilan 1 yilgacha"}, "en": {"text": "Georgia is visa-free for Uzbek citizens — up to one year on an international passport"}, "tr": {"text": "Gürcistan, Özbekistan vatandaşları için vizesiz — pasaportla 1 yıla kadar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'info' AND text = 'Грузия безвизовая для граждан Узбекистана — до 1 года по загранпаспорту';
UPDATE tour_content SET i18n = '{"uz": {"text": "5-kuni Turkiya–Gruziya chegarasidan quruqlikda o‘tiladi, avtobusda taxminan 3–4 soat"}, "en": {"text": "On day 5 there is a land border crossing Türkiye–Georgia, about 3–4 hours by coach"}, "tr": {"text": "5. gün Türkiye–Gürcistan kara sınırı geçişi, otobüsle yaklaşık 3–4 saat"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'info' AND text = 'На 5-й день — сухопутный переход границы Турция–Грузия, автобус около 3–4 часов';
UPDATE tour_content SET i18n = '{"uz": {"text": "Marshrut haqida video: Trabzon va Qora dengiz (Traveling Faze)"}, "en": {"text": "Video about the route: Trabzon and the Black Sea (Traveling Faze)"}, "tr": {"text": "Güzergâh videosu: Trabzon ve Karadeniz (Traveling Faze)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'info' AND text = 'Видео о маршруте: Трабзон и Чёрное море (Traveling Faze)';
UPDATE tour_content SET i18n = '{"uz": {"title": "1-kun · Batumi", "text": "Toshkent → Batumi, qo‘nish 23:20. Kutib olish, transfer, Batumi View Luxury mehmonxonasi. Kechki sayr va gruzin taomlari — ixtiyoriy."}, "en": {"title": "Day 1 · Batumi", "text": "Tashkent → Batumi, arrival 23:20. Meeting, transfer, Batumi View Luxury hotel. An evening walk and Georgian dinner are optional."}, "tr": {"title": "1. gün · Batum", "text": "Taşkent → Batum, iniş 23:20. Karşılama, transfer, Batumi View Luxury oteli. Akşam yürüyüşü ve Gürcü mutfağı — isteğe bağlı."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'A' AND text = 'Ташкент → Батуми, прилёт 23:20. Встреча, трансфер, отель Batumi View Luxury. Вечерняя прогулка и ужин грузинской кухни — по желанию.';
UPDATE tour_content SET i18n = '{"uz": {"title": "2-kun · Ajariya", "text": "Malika Tamara ko‘prigi, Mahuntseti sharsharasi, Gonio-Apsaros qal’asi. Tushlik: Batumi markazida gruzin yoki «Caravan»da o‘zbek taomlari. Ixtiyoriy zipline. Kechqurun — Mahuntsetida gruzin oilasida kechki ovqat."}, "en": {"title": "Day 2 · Adjara", "text": "Queen Tamar’s bridge, the Makhuntseti waterfall, the Gonio-Apsaros fortress. Lunch: Georgian food in central Batumi or Uzbek at “Caravan”. Zipline optional. In the evening, dinner with a Georgian family in Makhuntseti."}, "tr": {"title": "2. gün · Acara", "text": "Kraliçe Tamara Köprüsü, Mahuntseti Şelalesi, Gonio-Apsaros Kalesi. Öğle yemeği: Batum merkezinde Gürcü ya da «Caravan»da Özbek mutfağı. Zipline isteğe bağlı. Akşam Mahuntseti’de bir Gürcü ailesinde yemek."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'A' AND text = 'Мост царицы Тамары, водопад Махунцети, крепость Гонио-Апсарос. Обед: грузинская кухня в центре Батуми или узбекская в «Caravan». По желанию зиплайн. Вечером — ужин в грузинской семье в Махунцети.';
UPDATE tour_content SET i18n = '{"uz": {"title": "3–4-kunlar · Batumi", "text": "Bo‘sh kunlar: sohil bo‘yi, delfinariy (qo‘shimcha to‘lov), botanika bog‘i, xarid, eski shahar, Alifbo minorasi."}, "en": {"title": "Days 3–4 · Batumi", "text": "Free days: the promenade, the dolphinarium (extra charge), the botanical garden, shopping, the old town, the Alphabet Tower."}, "tr": {"title": "3–4. günler · Batum", "text": "Serbest günler: sahil bandı, yunus akvaryumu (ek ücret), botanik bahçe, alışveriş, eski şehir, Alfabe Kulesi."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'A' AND text = 'Свободные дни: набережная, дельфинарий (доплата), ботанический сад, шопинг, старый город, Башня Алфавита.';
UPDATE tour_content SET i18n = '{"uz": {"title": "5-kun · Batumi → Rize", "text": "Chegaradan o‘tib, avtobusda taxminan 3–4 soat yo‘l. Mehmonxona, kechki sayr, turk taomlari — ixtiyoriy."}, "en": {"title": "Day 5 · Batumi → Rize", "text": "About 3–4 hours by coach, including the border crossing. Hotel, an evening walk, Turkish dinner — optional."}, "tr": {"title": "5. gün · Batum → Rize", "text": "Sınır geçişiyle birlikte otobüsle yaklaşık 3–4 saat. Otel, akşam yürüyüşü, Türk mutfağı — isteğe bağlı."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'A' AND text = 'Переезд на автобусе около 3–4 часов с прохождением границы. Отель, вечерняя прогулка, ужин турецкой кухни — по желанию.';
UPDATE tour_content SET i18n = '{"uz": {"title": "6-kun · Uzungo‘l va Trabzon", "text": "Uzungo‘l ko‘li: choy va sovg‘alar. So‘ng to‘xtashlar bilan Trabzon — Karaca g‘ori, Torul Cam Teras manzaragohi. Kechqurun Forum AVMda xarid yoki shahar bo‘ylab sayr."}, "en": {"title": "Day 6 · Uzungöl and Trabzon", "text": "Lake Uzungöl: tea and souvenirs. Then on to Trabzon with stops — the Karaca cave and the Torul Cam Teras viewpoint. In the evening, shopping at Forum AVM or a walk in town."}, "tr": {"title": "6. gün · Uzungöl ve Trabzon", "text": "Uzungöl: çay ve hediyelik eşya. Ardından duraklarla Trabzon — Karaca Mağarası, Torul Cam Teras seyir terası. Akşam Forum AVM’de alışveriş ya da şehir turu."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'A' AND text = 'Озеро Узунгёль: чай и сувениры. Далее Трабзон с остановками — пещера Карача, смотровая Torul Cam Teras. Вечером шопинг Forum AVM или прогулка по городу.';
UPDATE tour_content SET i18n = '{"uz": {"title": "7-kun · Ayder", "text": "Choy plantatsiyalari orqali Ayder Yaylasi: Zilkale qal’asi, Palovit sharsharasi, 1350 m yassitog‘. Ixtiyoriy Huser tog‘i."}, "en": {"title": "Day 7 · Ayder", "text": "Ayder Yaylası through the tea plantations: Zilkale fortress, the Palovit waterfall, the plateau at 1350 m. Mount Huser optional."}, "tr": {"title": "7. gün · Ayder", "text": "Çay bahçelerinden geçerek Ayder Yaylası: Zilkale, Palovit Şelalesi, 1350 m yayla. İsteğe bağlı Huser Dağı."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'A' AND text = 'Айдер Яйласы через чайные плантации: крепость Zilkale, водопад Palovit, плато 1350 м. По желанию гора Хусер.';
UPDATE tour_content SET i18n = '{"uz": {"title": "8-kun · Uchish", "text": "Bo‘sh ertalab, aeroportga transfer. Trabzon → Toshkent, uchish 18:45."}, "en": {"title": "Day 8 · Departure", "text": "A free morning, transfer to the airport. Trabzon → Tashkent, departure 18:45."}, "tr": {"title": "8. gün · Dönüş", "text": "Serbest sabah, havalimanına transfer. Trabzon → Taşkent, kalkış 18:45."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'A' AND text = 'Свободное утро, трансфер в аэропорт. Трабзон → Ташкент, вылет 18:45.';
UPDATE tour_content SET i18n = '{"uz": {"title": "1-kun · Rize", "text": "Toshkent → Trabzon, qo‘nish 17:45. Kutib olish, transfer, Rhisos Gold Hotel Rize. Kechki sayr va turk taomlari — ixtiyoriy."}, "en": {"title": "Day 1 · Rize", "text": "Tashkent → Trabzon, arrival 17:45. Meeting, transfer, Rhisos Gold Hotel Rize. An evening walk and Turkish dinner are optional."}, "tr": {"title": "1. gün · Rize", "text": "Taşkent → Trabzon, iniş 17:45. Karşılama, transfer, Rhisos Gold Hotel Rize. Akşam yürüyüşü ve Türk mutfağı — isteğe bağlı."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'B' AND text = 'Ташкент → Трабзон, прилёт 17:45. Встреча, трансфер, отель Rhisos Gold Hotel Rize. Вечерняя прогулка и ужин турецкой кухни — по желанию.';
UPDATE tour_content SET i18n = '{"uz": {"title": "2-kun · Uzungo‘l va Trabzon", "text": "Uzungo‘l ko‘li, so‘ng Trabzon: Karaca g‘ori, Torul Cam Teras manzaragohi. Kechqurun Forum AVMda xarid yoki shahar bo‘ylab sayr."}, "en": {"title": "Day 2 · Uzungöl and Trabzon", "text": "Lake Uzungöl, then Trabzon: the Karaca cave and the Torul Cam Teras viewpoint. In the evening, shopping at Forum AVM or a walk in town."}, "tr": {"title": "2. gün · Uzungöl ve Trabzon", "text": "Uzungöl, ardından Trabzon: Karaca Mağarası, Torul Cam Teras. Akşam Forum AVM’de alışveriş ya da şehir turu."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'B' AND text = 'Озеро Узунгёль, далее Трабзон: пещера Карача, смотровая Torul Cam Teras. Вечером шопинг Forum AVM или прогулка по городу.';
UPDATE tour_content SET i18n = '{"uz": {"title": "3-kun · Ayder", "text": "Ayder Yaylasi: Zilkale qal’asi, Palovit sharsharasi, 1350 m yassitog‘. Ixtiyoriy Huser tog‘i."}, "en": {"title": "Day 3 · Ayder", "text": "Ayder Yaylası: Zilkale fortress, the Palovit waterfall, the plateau at 1350 m. Mount Huser optional."}, "tr": {"title": "3. gün · Ayder", "text": "Ayder Yaylası: Zilkale, Palovit Şelalesi, 1350 m yayla. İsteğe bağlı Huser Dağı."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'B' AND text = 'Айдер Яйласы: крепость Zilkale, водопад Palovit, плато 1350 м. По желанию гора Хусер.';
UPDATE tour_content SET i18n = '{"uz": {"title": "4-kun · Rize", "text": "Bo‘sh kun: xarid, sohil bo‘yi, kafelar. Duatepe va Ceceve Bahcesi ekskursiyalari — qo‘shimcha to‘lov evaziga."}, "en": {"title": "Day 4 · Rize", "text": "A free day: shopping, the promenade, cafés. The Duatepe and Ceceve Bahcesi excursions are available at extra cost."}, "tr": {"title": "4. gün · Rize", "text": "Serbest gün: alışveriş, sahil, kafeler. Duatepe ve Ceceve Bahçesi gezileri — ek ücretle."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'B' AND text = 'Свободный день: шопинг, набережная, кафе. Дополнительные экскурсии Duatepe и Ceceve Bahcesi — за доплату.';
UPDATE tour_content SET i18n = '{"uz": {"title": "5-kun · Rize → Batumi", "text": "Chegaradan o‘tib, avtobusda taxminan 3–4 soat yo‘l. Batumi View Luxury mehmonxonasi, kechki sayr — ixtiyoriy."}, "en": {"title": "Day 5 · Rize → Batumi", "text": "About 3–4 hours by coach, including the border crossing. Batumi View Luxury hotel, an evening walk — optional."}, "tr": {"title": "5. gün · Rize → Batum", "text": "Sınır geçişiyle birlikte otobüsle yaklaşık 3–4 saat. Batumi View Luxury oteli, akşam yürüyüşü — isteğe bağlı."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'B' AND text = 'Переезд на автобусе около 3–4 часов с прохождением границы. Отель Batumi View Luxury, вечерняя прогулка — по желанию.';
UPDATE tour_content SET i18n = '{"uz": {"title": "6-kun · Ajariya", "text": "Batumida yoki «Caravan»da tushlik. Malika Tamara ko‘prigi, Mahuntseti sharsharasi, Gonio-Apsaros qal’asi. Ixtiyoriy zipline. Kechqurun — Mahuntsetida gruzin oilasida kechki ovqat."}, "en": {"title": "Day 6 · Adjara", "text": "Lunch in Batumi or at “Caravan”. Queen Tamar’s bridge, the Makhuntseti waterfall, the Gonio-Apsaros fortress. Zipline optional. In the evening, dinner with a Georgian family in Makhuntseti."}, "tr": {"title": "6. gün · Acara", "text": "Batum’da ya da «Caravan»da öğle yemeği. Kraliçe Tamara Köprüsü, Mahuntseti Şelalesi, Gonio-Apsaros Kalesi. Zipline isteğe bağlı. Akşam Mahuntseti’de bir Gürcü ailesinde yemek."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'B' AND text = 'Обед в Батуми или в «Caravan». Мост царицы Тамары, водопад Махунцети, крепость Гонио-Апсарос. По желанию зиплайн. Вечером — ужин в грузинской семье в Махунцети.';
UPDATE tour_content SET i18n = '{"uz": {"title": "7–8-kunlar · Batumi", "text": "Bo‘sh kunlar: sohil bo‘yi, delfinariy (qo‘shimcha to‘lov), botanika bog‘i, xarid, eski shahar, Alifbo minorasi. 8-kuni Batumidan uchish."}, "en": {"title": "Days 7–8 · Batumi", "text": "Free days: the promenade, the dolphinarium (extra charge), the botanical garden, shopping, the old town, the Alphabet Tower. Day 8 — departure from Batumi."}, "tr": {"title": "7–8. günler · Batum", "text": "Serbest günler: sahil bandı, yunus akvaryumu (ek ücret), botanik bahçe, alışveriş, eski şehir, Alfabe Kulesi. 8. gün Batum’dan dönüş."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'KARADENIZ') AND kind = 'day' AND variant = 'B' AND text = 'Свободные дни: набережная, дельфинарий (доплата), ботанический сад, шопинг, старый город, Башня Алфавита. День 8 — вылет из Батуми.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Jidda · Hawada Hotel Jeddah · 1 kecha"}, "en": {"text": "Jeddah · Hawada Hotel Jeddah · 1 night"}, "tr": {"text": "Cidde · Hawada Hotel Jeddah · 1 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'included' AND text = 'Джидда · Hawada Hotel Jeddah · 1 ночь';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Taj Park · Haramgacha 990 m · 8 kecha"}, "en": {"text": "Mecca · Taj Park · 990 m to the Haram · 8 nights"}, "tr": {"text": "Mekke · Taj Park · Harem’e 990 m · 8 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'included' AND text = 'Мекка · Taj Park · 990 м до Харама · 8 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Grand Al Shahba · Payg‘ambar masjidigacha 250 m · 3 kecha"}, "en": {"text": "Medina · Grand Al Shahba · 250 m to the Prophet’s Mosque · 3 nights"}, "tr": {"text": "Medine · Grand Al Shahba · Mescid-i Nebevi’ye 250 m · 3 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'included' AND text = 'Медина · Grand Al Shahba · 250 м до мечети Пророка · 3 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka—Madina avtobusi"}, "en": {"text": "Mecca—Medina coach"}, "tr": {"text": "Mekke—Medine otobüsü"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'included' AND text = 'Автобус Мекка—Медина';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka va Madinada uch mahal ovqat"}, "en": {"text": "Three meals a day in Mecca and Medina"}, "tr": {"text": "Mekke ve Medine’de üç öğün yemek"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'included' AND text = 'Трёхразовое питание в Мекке и Медине';
UPDATE tour_content SET i18n = '{"uz": {"text": "Jiddada 1 mahal ovqat"}, "en": {"text": "One meal in Jeddah"}, "tr": {"text": "Cidde’de bir öğün"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'included' AND text = '1 питание в Джидде';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Avgust—sentabr har hafta; kuzgi jo‘nashlar (oktabr—dekabr) operator bilan aniqlanadi."}, "en": {"text": "Weekly in August–September; autumn departures (October–December) to be confirmed with the operator."}, "tr": {"text": "Ağustos–Eylül her hafta; sonbahar hareketleri (Ekim–Aralık) operatörle netleştirilir."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13') AND kind = 'info' AND text = 'Август—сентябрь еженедельно; осенние заезды (октябрь—декабрь) уточняются у оператора.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Jidda · Hawada Hotel Jeddah · 1 kecha"}, "en": {"text": "Jeddah · Hawada Hotel Jeddah · 1 night"}, "tr": {"text": "Cidde · Hawada Hotel Jeddah · 1 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'included' AND text = 'Джидда · Hawada Hotel Jeddah · 1 ночь';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Taj Park · Haramgacha 990 m · 8 kecha"}, "en": {"text": "Mecca · Taj Park · 990 m to the Haram · 8 nights"}, "tr": {"text": "Mekke · Taj Park · Harem’e 990 m · 8 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'included' AND text = 'Мекка · Taj Park · 990 м до Харама · 8 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Mukhtara Plaza · Payg‘ambar masjidigacha 250 m · 3 kecha"}, "en": {"text": "Medina · Mukhtara Plaza · 250 m to the Prophet’s Mosque · 3 nights"}, "tr": {"text": "Medine · Mukhtara Plaza · Mescid-i Nebevi’ye 250 m · 3 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'included' AND text = 'Медина · Mukhtara Plaza · 250 м до мечети Пророка · 3 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka—Madina tezyurar poyezdi"}, "en": {"text": "Mecca—Medina high-speed train"}, "tr": {"text": "Mekke—Medine hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'included' AND text = 'Скоростной поезд Мекка—Медина';
UPDATE tour_content SET i18n = '{"uz": {"text": "Ovqat: Jidda 1 marta, Makka 3 marta, Madina 2 marta (ochiq bufet)"}, "en": {"text": "Meals: Jeddah once, Mecca three times, Medina twice (buffet)"}, "tr": {"text": "Öğün: Cidde 1, Mekke 3, Medine 2 (açık büfe)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'included' AND text = 'Питание: Джидда 1 раз, Мекка 3 раза, Медина 2 раза (шведский стол)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Iyul—avgust — ko‘rsatilgan sanalarda."}, "en": {"text": "July–August, on the dates listed."}, "tr": {"text": "Temmuz–Ağustos, belirtilen tarihlerde."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_TAJ13P') AND kind = 'info' AND text = 'Июль—август по указанным датам.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Jidda · Hawada Hotel Jeddah · 1 kecha"}, "en": {"text": "Jeddah · Hawada Hotel Jeddah · 1 night"}, "tr": {"text": "Cidde · Hawada Hotel Jeddah · 1 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'included' AND text = 'Джидда · Hawada Hotel Jeddah · 1 ночь';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Anjum · Haramgacha 250 m · 8 kecha"}, "en": {"text": "Mecca · Anjum · 250 m to the Haram · 8 nights"}, "tr": {"text": "Mekke · Anjum · Harem’e 250 m · 8 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'included' AND text = 'Мекка · Anjum · 250 м до Харама · 8 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 3 kecha"}, "en": {"text": "Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 3 nights"}, "tr": {"text": "Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 3 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'included' AND text = 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka—Madina tezyurar poyezdi"}, "en": {"text": "Mecca—Medina high-speed train"}, "tr": {"text": "Mekke—Medine hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'included' AND text = 'Скоростной поезд Мекка—Медина';
UPDATE tour_content SET i18n = '{"uz": {"text": "Ovqat: Jidda 1 marta, Makka 1 marta, Madina 2 marta (ochiq bufet)"}, "en": {"text": "Meals: Jeddah once, Mecca once, Medina twice (buffet)"}, "tr": {"text": "Öğün: Cidde 1, Mekke 1, Medine 2 (açık büfe)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'included' AND text = 'Питание: Джидда 1 раз, Мекка 1 раз, Медина 2 раза (шведский стол)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Avgust — ko‘rsatilgan sanalarda."}, "en": {"text": "August, on the dates listed."}, "tr": {"text": "Ağustos, belirtilen tarihlerde."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM13') AND kind = 'info' AND text = 'Август по указанным датам.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Jidda · Hawada Hotel Jeddah · 1 kecha"}, "en": {"text": "Jeddah · Hawada Hotel Jeddah · 1 night"}, "tr": {"text": "Cidde · Hawada Hotel Jeddah · 1 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'included' AND text = 'Джидда · Hawada Hotel Jeddah · 1 ночь';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Al Shohada · Haramgacha 250 m · 8 kecha"}, "en": {"text": "Mecca · Al Shohada · 250 m to the Haram · 8 nights"}, "tr": {"text": "Mekke · Al Shohada · Harem’e 250 m · 8 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'included' AND text = 'Мекка · Al Shohada · 250 м до Харама · 8 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 3 kecha"}, "en": {"text": "Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 3 nights"}, "tr": {"text": "Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 3 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'included' AND text = 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka—Madina tezyurar poyezdi"}, "en": {"text": "Mecca—Medina high-speed train"}, "tr": {"text": "Mekke—Medine hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'included' AND text = 'Скоростной поезд Мекка—Медина';
UPDATE tour_content SET i18n = '{"uz": {"text": "Ovqat: Jidda 1 marta, Makka va Madina 2 martadan (ochiq bufet)"}, "en": {"text": "Meals: Jeddah once, Mecca and Medina twice each (buffet)"}, "tr": {"text": "Öğün: Cidde 1, Mekke ve Medine 2’şer (açık büfe)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'included' AND text = 'Питание: Джидда 1 раз, Мекка и Медина 2 раза (шведский стол)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Avgust — ko‘rsatilgan sanalarda."}, "en": {"text": "August, on the dates listed."}, "tr": {"text": "Ağustos, belirtilen tarihlerde."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SHOHADA13') AND kind = 'info' AND text = 'Август по указанным датам.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Jidda · Hawada Hotel Jeddah · 1 kecha"}, "en": {"text": "Jeddah · Hawada Hotel Jeddah · 1 night"}, "tr": {"text": "Cidde · Hawada Hotel Jeddah · 1 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'included' AND text = 'Джидда · Hawada Hotel Jeddah · 1 ночь';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Jumeirah Hotel · Haramgacha 100 m · 8 kecha"}, "en": {"text": "Mecca · Jumeirah Hotel · 100 m to the Haram · 8 nights"}, "tr": {"text": "Mekke · Jumeirah Hotel · Harem’e 100 m · 8 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'included' AND text = 'Мекка · Jumeirah Hotel · 100 м до Харама · 8 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 3 kecha"}, "en": {"text": "Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 3 nights"}, "tr": {"text": "Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 3 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'included' AND text = 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 3 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka—Madina tezyurar poyezdi"}, "en": {"text": "Mecca—Medina high-speed train"}, "tr": {"text": "Mekke—Medine hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'included' AND text = 'Скоростной поезд Мекка—Медина';
UPDATE tour_content SET i18n = '{"uz": {"text": "Ovqat: Jidda 1 marta, Makka 1 marta, Madina 2 marta (ochiq bufet)"}, "en": {"text": "Meals: Jeddah once, Mecca once, Medina twice (buffet)"}, "tr": {"text": "Öğün: Cidde 1, Mekke 1, Medine 2 (açık büfe)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'included' AND text = 'Питание: Джидда 1 раз, Мекка 1 раз, Медина 2 раза (шведский стол)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Avgust — ko‘rsatilgan sanalarda."}, "en": {"text": "August, on the dates listed."}, "tr": {"text": "Ağustos, belirtilen tarihlerde."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH13') AND kind = 'info' AND text = 'Август по указанным датам.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Saja Al-Madinah · Payg‘ambar masjidigacha 250 m · 4 kecha"}, "en": {"text": "Medina · Saja Al-Madinah · 250 m to the Prophet’s Mosque · 4 nights"}, "tr": {"text": "Medine · Saja Al-Madinah · Mescid-i Nebevi’ye 250 m · 4 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SAJA10') AND kind = 'included' AND text = 'Медина · Saja Al-Madinah · 250 м до мечети Пророка · 4 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Taj Park · Haramgacha 990 m · 5 kecha"}, "en": {"text": "Mecca · Taj Park · 990 m to the Haram · 5 nights"}, "tr": {"text": "Mekke · Taj Park · Harem’e 990 m · 5 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SAJA10') AND kind = 'included' AND text = 'Мекка · Taj Park · 990 м до Харама · 5 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina—Makka tezyurar poyezdi"}, "en": {"text": "Medina—Mecca high-speed train"}, "tr": {"text": "Medine—Mekke hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SAJA10') AND kind = 'included' AND text = 'Скоростной поезд Медина—Мекка';
UPDATE tour_content SET i18n = '{"uz": {"text": "Uch mahal ovqat"}, "en": {"text": "Three meals a day"}, "tr": {"text": "Üç öğün yemek"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SAJA10') AND kind = 'included' AND text = 'Трёхразовое питание';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SAJA10') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SAJA10') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Iyul—sentabr har hafta; kuzgi jo‘nashlar (oktabr—dekabr) operator bilan aniqlanadi."}, "en": {"text": "Weekly in July–September; autumn departures (October–December) to be confirmed with the operator."}, "tr": {"text": "Temmuz–Eylül her hafta; sonbahar hareketleri (Ekim–Aralık) operatörle netleştirilir."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SAJA10') AND kind = 'info' AND text = 'Июль—сентябрь еженедельно; осенние заезды (октябрь—декабрь) уточняются у оператора.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 4 kecha"}, "en": {"text": "Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 4 nights"}, "tr": {"text": "Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 4 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SWISS10') AND kind = 'included' AND text = 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Swissotel Makkah · Haramgacha 50 m · 5 kecha"}, "en": {"text": "Mecca · Swissotel Makkah · 50 m to the Haram · 5 nights"}, "tr": {"text": "Mekke · Swissotel Makkah · Harem’e 50 m · 5 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SWISS10') AND kind = 'included' AND text = 'Мекка · Swissotel Makkah · 50 м до Харама · 5 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina—Makka tezyurar poyezdi"}, "en": {"text": "Medina—Mecca high-speed train"}, "tr": {"text": "Medine—Mekke hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SWISS10') AND kind = 'included' AND text = 'Скоростной поезд Медина—Мекка';
UPDATE tour_content SET i18n = '{"uz": {"text": "Ovqat: Makka 1 marta, Madina 2 marta (ochiq bufet)"}, "en": {"text": "Meals: Mecca once, Medina twice (buffet)"}, "tr": {"text": "Öğün: Mekke 1, Medine 2 (açık büfe)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SWISS10') AND kind = 'included' AND text = 'Питание: Мекка 1 раз, Медина 2 раза (шведский стол)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SWISS10') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SWISS10') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "6 avgustdan 3 dekabrgacha har hafta — aniq sanalar operator bilan aniqlanadi."}, "en": {"text": "Weekly from 6 August to 3 December — exact dates to be confirmed with the operator."}, "tr": {"text": "6 Ağustos–3 Aralık arası her hafta — kesin tarihler operatörle netleştirilir."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_SWISS10') AND kind = 'info' AND text = 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 4 kecha"}, "en": {"text": "Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 4 nights"}, "tr": {"text": "Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 4 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM10') AND kind = 'included' AND text = 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Anjum Makkah · Haramgacha 250 m · 5 kecha"}, "en": {"text": "Mecca · Anjum Makkah · 250 m to the Haram · 5 nights"}, "tr": {"text": "Mekke · Anjum Makkah · Harem’e 250 m · 5 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM10') AND kind = 'included' AND text = 'Мекка · Anjum Makkah · 250 м до Харама · 5 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina—Makka tezyurar poyezdi"}, "en": {"text": "Medina—Mecca high-speed train"}, "tr": {"text": "Medine—Mekke hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM10') AND kind = 'included' AND text = 'Скоростной поезд Медина—Мекка';
UPDATE tour_content SET i18n = '{"uz": {"text": "Ovqat: Makka 1 marta, Madina 2 marta (ochiq bufet)"}, "en": {"text": "Meals: Mecca once, Medina twice (buffet)"}, "tr": {"text": "Öğün: Mekke 1, Medine 2 (açık büfe)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM10') AND kind = 'included' AND text = 'Питание: Мекка 1 раз, Медина 2 раза (шведский стол)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM10') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM10') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "6 avgustdan 3 dekabrgacha har hafta — aniq sanalar operator bilan aniqlanadi."}, "en": {"text": "Weekly from 6 August to 3 December — exact dates to be confirmed with the operator."}, "tr": {"text": "6 Ağustos–3 Aralık arası her hafta — kesin tarihler operatörle netleştirilir."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_ANJUM10') AND kind = 'info' AND text = 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina · Waqf Al Safi · Payg‘ambar masjidigacha 50 m · 4 kecha"}, "en": {"text": "Medina · Waqf Al Safi · 50 m to the Prophet’s Mosque · 4 nights"}, "tr": {"text": "Medine · Waqf Al Safi · Mescid-i Nebevi’ye 50 m · 4 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH10') AND kind = 'included' AND text = 'Медина · Waqf Al Safi · 50 м до мечети Пророка · 4 ночи';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka · Jumeirah Jabal Omar · Haramgacha 100 m · 5 kecha"}, "en": {"text": "Mecca · Jumeirah Jabal Omar · 100 m to the Haram · 5 nights"}, "tr": {"text": "Mekke · Jumeirah Jabal Omar · Harem’e 100 m · 5 gece"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH10') AND kind = 'included' AND text = 'Мекка · Jumeirah Jabal Omar · 100 м до Харама · 5 ночей';
UPDATE tour_content SET i18n = '{"uz": {"text": "Madina—Makka tezyurar poyezdi"}, "en": {"text": "Medina—Mecca high-speed train"}, "tr": {"text": "Medine—Mekke hızlı treni"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH10') AND kind = 'included' AND text = 'Скоростной поезд Медина—Мекка';
UPDATE tour_content SET i18n = '{"uz": {"text": "Makka va Madinada 2 martadan ovqat (ochiq bufet)"}, "en": {"text": "Meals twice a day in Mecca and Medina (buffet)"}, "tr": {"text": "Mekke ve Medine’de günde 2 öğün (açık büfe)"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH10') AND kind = 'included' AND text = 'Питание в Мекке и Медине 2 раза (шведский стол)';
UPDATE tour_content SET i18n = '{"uz": {"text": "Viza"}, "en": {"text": "Visa"}, "tr": {"text": "Vize"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH10') AND kind = 'included' AND text = 'Виза';
UPDATE tour_content SET i18n = '{"uz": {"text": "Guruh rahbarlari va shifokorlar"}, "en": {"text": "Group leaders and doctors"}, "tr": {"text": "Grup liderleri ve doktorlar"}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH10') AND kind = 'included' AND text = 'Руководители группы и врачи';
UPDATE tour_content SET i18n = '{"uz": {"text": "6 avgustdan 3 dekabrgacha har hafta — aniq sanalar operator bilan aniqlanadi."}, "en": {"text": "Weekly from 6 August to 3 December — exact dates to be confirmed with the operator."}, "tr": {"text": "6 Ağustos–3 Aralık arası her hafta — kesin tarihler operatörle netleştirilir."}}' WHERE tour_id = (SELECT id FROM tours WHERE code = 'UMRA_JUMEIRAH10') AND kind = 'info' AND text = 'Еженедельно с 6 августа по 3 декабря — точные даты уточняются у оператора.';

-- строк обновляется — tours: 10, destinations: 2, tour_variants: 2, tour_content: 99
