import { chromium } from "playwright";
const S="/tmp/claude-0/-home-user/c443b3cc-a24d-5a7f-a6e5-c3857f2dfc61/scratchpad/";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await b.newContext({ viewport: { width: 900, height: 1200 } });
const p = await ctx.newPage();
p.on("pageerror", e => console.log("ERR", String(e).slice(0,220)));
await p.goto("http://127.0.0.1:8899/preview.html", { waitUntil: "networkidle" });
await p.evaluate(() => { window.location.hash = "#/login"; });
await p.waitForTimeout(700);
await p.fill("#l-login","umida"); await p.fill("#l-password","turon2026");
await p.click("#login-btn"); await p.waitForTimeout(1300);
await p.evaluate(() => { window.location.hash = "#/app/departures"; });
await p.waitForTimeout(1300);
await (await p.$("[data-book]")).click(); await p.waitForTimeout(800);
const add = await p.$("#bm-add"); if (add) await add.click();
await p.waitForTimeout(400);
const n = await p.locator("#bm-passengers .tt-pax").count();
const names=["TUYCHIEV MUKHTARJON","BAKHRAMOV BOTIR"], bd=["1957-06-17","1950-03-15"], pn=["FB2734877","FA6935856"];
for (let i=0;i<n;i++){const c=p.locator("#bm-passengers .tt-pax").nth(i);
  await c.locator('[data-f="full_name"]').fill(names[i]||"PAX");
  await c.locator('[data-f="birth_date"]').fill(bd[i]||"1980-01-01");
  await c.locator('[data-f="passport_number"]').fill(pn[i]||"AA1111111");
  await c.locator('[data-f="passport_expiry"]').fill("2032-01-01");}
await p.waitForTimeout(500); await p.locator("#bm-submit").click(); await p.waitForTimeout(1300);
await p.evaluate(() => { window.location.hash = "#/app/documents"; });
await p.waitForTimeout(1100);
const [w] = await Promise.all([ctx.waitForEvent("page"), (await p.$("[data-ticket]")).click()]);
await w.waitForLoadState("load"); await w.waitForTimeout(1200);
await w.screenshot({ path: S+"t2.png", fullPage: true });
console.log("готово");
await b.close();
